# Generated by Django 5.2 on 2025-04-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('trust_score', models.IntegerField(default=0)),
                ('transaction_count', models.IntegerField(default=0)),
            ],
        ),
    ]
