# Generated by Django 5.2 on 2025-05-19 13:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('exchange', 'Exchange')], default='sale', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20, null=True)),
                ('canceled_by', models.CharField(blank=True, choices=[('buyer', 'Buyer'), ('seller', 'Seller')], max_length=20, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='books.book')),
            ],
        ),
    ]
